#! /bin/bash

#ECHO COMMAND
echo Hello World!

#VARIABLES
#Upper case by conventions
#Letters, numbers, underscores
NAME="CODYCODE"
#echo "My name is $NAME"
#fix this over the weekend
#USER INPUT
read -p "Enter your name: "NAME"
echo "Hello $NAME, do you know how to write Python code?"
